<?php echo $this->doctype('XHTML1_STRICT'); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

<?php 
$this->headMeta()->appendName('keywords', $this->config->user->metaKeywords->val)
                 ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                 ->appendHttpEquiv('Content-Language', 'en-US');             
                 
echo $this->headMeta() . "\n";

$this->headTitle($this->config->user->appTitle->val)
     ->headTitle(strip_tags($this->title))
     ->headTitle()->setSeparator(' - ');

echo "\n";
     
echo $this->headTitle() . "\n\n";

$this->headLink()->appendStylesheet($this->themeBaseUrl() . '/public/css/twocolumn.css');

//print the minified (common) css first, then the autoloaded css
echo $this->minifyHeadLink() . "\n";
echo $this->headLink() . "\n\n";

// print the minified (common) scripts first, then the autoloaded scripts
echo $this->minifyHeadScript() . "\n";
echo $this->headScript() . "\n";


$this->overrideTranslation()->js(); 
echo "\n";
?>
</head>
<body>
    <input type="hidden" name="baseUrl" id="baseUrl" value="<?php echo $this->baseUrl(); ?>" />
    <div id="custom-doc" class="yui-t7">
        <?php echo $this->render('header.phtml'); ?>
        <div id="bd">
            <div id="bdInner">            
                <div class="yui-ge">
                	<div id="leftColumn" class="yui-u first">
                		<div id="paperHeaderSmall"></div>                		
                		<div id="paperContentSmall">
                			<div class="ui-helper-clearfix"></div>
                        <?php if (!empty($this->messages) != 0) : ?>
                            <div id="systemMessages" class="ui-state-highlight ui-corner-all">
                                <span class="ui-icon ui-icon-info"></span>
                                    <?php foreach ($this->messages as $m) : ?>
                                        <?php echo $this->translate($m); ?><br />
                                    <?php endforeach; ?>
                            </div>
                       <?php endif; ?>                		
                			<?php echo $this->layout()->content; ?>
                			<div class="ui-helper-clearfix"></div>
                		</div>
                		<div id="paperFooterSmall"></div>
                	</div>
                	<div id="rightColumn" class="yui-u">
                		<div id="corkHeaderSmall"></div>
                		<div id="corkContentSmall">
                			<?php echo $this->layout()->rightContent; ?>
                			<div class="ui-helper-clearfix"></div>
                		</div>
                		<div id="corkFooterSmall"></div>
                	</div>
                </div>
                <?php $this->overrideTranslation()->link('Edit Text For This Page'); ?>
            </div>
        </div>
        <div id="ft">
            <div id="ftInner">
                <?php echo $this->render('footer.phtml'); ?>
            </div>
        </div>
    </div>
</body>
</html>