<?php echo $this->translate("workshop-index-index:header"); ?>
<?php echo $this->form; ?>
<?php if (count($this->workshops) > 0):
?>
    <?php if ($this->searchTerm != ''):?>
    <h3><?php echo $this->translate("workshop-index-index:searchResults", array($this->searchTerm, count($this->workshops))); ?></h3>
    <?php else:?>
    <h3><?php echo $this->translate("workshop-index-index:categoryResults", array(count($this->workshops))); ?></h3>
    <?php endif;?>
    <br />
    <?php foreach ($this->workshops as $w): ?>
        <div class="searchResult">
            <div class="title"><a href="<?php echo $this->url(array('module' => 'workshop', 'controller' => 'index', 'action' => 'details', 'workshopId' => $w->workshopId), 'default', true); ?>"><?php echo $w->title; ?></a></div>
            <div class="description"><?php echo $this->truncate(strip_tags($w->description), 200); ?></div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>