<?php echo $this->translate("workshop-index-index:header"); ?>
<?php echo $this->form; ?>
<?php if ($this->searchTerm != ''): ?>
	<h3><?php echo $this->translate("workshop-index-index:results", array($this->searchTerm, count($this->workshops))); ?></h3>
	<br />
	<?php foreach ($this->workshops as $w): ?>
	    <div class="searchResult">
		    <div class="title"><a href="<?php echo $this->baseUrl(); ?>/workshop/index/details/?workshopId=<?php echo $w->workshopId; ?>"><?php echo $w->title; ?></a></div>
		    <div class="description"><?php echo $this->truncate(strip_tags($w->description), 200); ?></div>
		</div>
	<?php endforeach; ?>
<?php endif; ?>