<?php if (count($this->workshops) > 0): ?>
    <?php foreach ($this->workshops as $w): ?>
        <div class="workshop">
            <div class="title">
                <a href="<?php echo $this->url(array('module' => 'workshop', 'controller' => 'index', 'action' => 'details', 'workshopId' => $w['workshopId']), 'default', true); ?>"><?php echo $w['title']; ?></a>
                <?php if ($w['status'] == 'disabled') : ?>
                    <span class="disabled">(DISABLED)</span>
                <?php endif; ?>
            </div>
            <div class="description"><?php echo $this->truncate(strip_tags($w['description']), 200); ?></div>
        </div>
    <?php endforeach; ?>
<?php else : ?>
    No workshops found
<?php endif; ?>