<div id="logoBox">
    <div id="brandingBar">
        <div id="brandingBarInner">
            <div id="brandingLinks">
                <a id="ncsuBrandingLink" target="_blank" href="http://www.ncsu.edu"><span>ncsu.edu</span></a>
                <a id="oitBrandingLink" target="_blank" href="http://oit.ncsu.edu"><span>oit.ncsu.edu</span></a>
            </div>
            <div class="authInfo"><?php echo $this->render('auth.phtml'); ?></div>
        </div>
    </div>  
    <div class="ui-helper-clearfix"></div>         
    <a id="homeLink" href="<?php echo $this->baseUrl(); ?>">        
        <span id="oitLogo"> 
            <span class="title"><?php echo $this->varReg('appTitle'); ?></span>
        </span>  
    </a>
    <br /><br />
</div>
<div id="header-nav-menu">
<?php echo $this->render('nav.phtml'); ?>
</div>