<div id="footer" align="center">
    <div class="floatLeft">
        &copy; <?php echo date('Y'); ?> <a href="http://www.ncsu.edu">North Carolina State University</a><br />
    	<a href="http://oit.ncsu.edu">Office of Information Technology</a><br />
    	<a href="http://webapps.ncsu.edu/">Outreach Technology</a>
    </div>
    <div class="floatRight">
        <a id="oitLogo" href="http://oit.ncsu.edu" target="_blank"></a>            
    </div>    
</div>