<div id="brandingBar">
    <div id="brandingBarInner">
        <div id="brandingLinks">
            <a id="ncsuBrandingLink" target="_blank" href="http://www.ncsu.edu"><span>ncsu.edu</span></a>
            <a id="oitBrandingLink" target="_blank" href="http://oit.ncsu.edu"><span>oit.ncsu.edu</span></a>
        </div>
        <div class="authInfo"><?php echo $this->render('auth.phtml'); ?></div>
    </div>
</div>
<div id="hd">
    <div id="hdInner">
        <a href="<?php echo $this->baseUrl(); ?>" id="homeLink"><span>Click to go Home</span></a>
        <div id="navBar">
            <?php echo $this->render('nav.phtml'); ?>
        </div>
    </div>
</div>