<?php echo $this->doctype('XHTML1_STRICT'); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

<?php 
$this->headMeta()->appendName('keywords', $this->config->user->metaKeywords->val)
                 ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                 ->appendHttpEquiv('Content-Language', 'en-US');             
                 
echo $this->headMeta() . "\n";

$this->headTitle($this->config->user->appTitle->val)
     ->headTitle(strip_tags($this->title))
     ->headTitle()->setSeparator(' - ');

echo "\n";
     
echo $this->headTitle() . "\n\n";

//print the minified (common) css first, then the autoloaded css
echo $this->minifyHeadLink() . "\n";
echo $this->headLink() . "\n\n";

// print the minified (common) scripts first, then the autoloaded scripts
echo $this->minifyHeadScript() . "\n";
echo $this->headScript() . "\n";


$this->overrideTranslation()->js(); 
echo "\n";
?>
</head>
<body>
    <input type="hidden" name="baseUrl" id="baseUrl" value="<?php echo $this->baseUrl(); ?>" />
    <div id="doc2" class="yui-t7">
        <div id="hd">
            <?php echo $this->render('header.phtml'); ?>
        </div>
        <div id="bd">           
            <div id="yui-main">
                <div class="yui-b">
                    <div class="yui-g" id="mainContent">
                        <div class="contentBody">
                            <?php if (!empty($this->messages) != 0) : ?>
                            <div id="systemMessages" class="ui-state-highlight ui-corner-all">
                                <span class="ui-icon ui-icon-info"></span>
                                    <?php foreach ($this->messages as $m) : ?>
                                        <?php echo $this->translate($m); ?><br />
                                    <?php endforeach; ?>
                            </div>
                            <?php endif; ?>
                            <div id="pageTitle"><?php echo $this->title; ?></div>
                            <div class="yui-u first">
                                <div class="homepageHeader ui-state-default">Upcoming Classes</div>
                                <div class="homepageContent">
                                    <div id="paper">
                                        <div>
                                        <?php echo $this->translate('default-index-index:checkOut'); ?>
                                        </div>
                                    </div>
                                    <?php echo $this->comingEvents($this->upcoming, 3); ?>
                                </div>
                            </div>    
                            <div class="yui-u">
                                <div class="homepageHeader ui-state-default">
                                    <?php if ($this->isLoggedIn): ?>
                                    <?php echo $this->translate("default-index-history:currentEvents", array($this->account['firstName'], $this->account['lastName'])); ?>
                                    <?php else: ?>
                                    <?php echo $this->translate("default-index-index:myCurrent"); ?>
                                    <?php endif; ?>
                                    </div>
                                <div class="homepageContent">
                                <?php echo $this->layout()->content; ?>
                                </div>
                            </div>
                            
                            <div class="ui-helper-clearfix"></div>                            
                            
                            <?php $this->overrideTranslation()->link('Edit Text For This Page'); ?> 
                        </div>  
                    </div>
                </div>
            </div>
        </div>
        <div id="ft">
           <?php echo $this->render('footer.phtml'); ?>
        </div>
    </div>
</body>
</html>