<html>    
    <body onload="window.print();">
        <div style="font-size: 1.2em; margin-bottom: 5px; font-weight: bold; text-align: center;"><?php echo $this->workshop['title']; ?></div>
        <div style="text-align: center; margin-bottom: 5px;"><?php echo $this->location['name']; ?></div>
        <div style="text-align: center; margin-bottom: 5px;">
            <?php echo $this->dateFormat($this->event['date'], $this->config->user->longDateFormat->val); ?> 
            (<?php echo $this->dateFormat($this->event['startTime'], $this->config->user->timeFormat->val); ?> -
            <?php echo $this->dateFormat($this->event['endTime'], $this->config->user->timeFormat->val); ?>)
        </div>
        <div style="text-align: center; margin-bottom: 5px;">
            Instructor<?php echo (count($this->instructors) != 1) ? 's' : ''; ?>: <?php echo implode(',', $this->instructors); ?>
        </div>
        
        <table width="90%" style="margin-top: 50px;">
            <tbody>
                <?php foreach ($this->attendeeList as $a) : ?>
                    <tr>
                        <td width="40%"><?php echo $a['firstName'] ?> <?php echo $a['lastName']; ?></td>
                        <td width="60%" style="border-bottom: 1px solid #000;">&nbsp;</td>
                    </tr>                
                <?php endforeach; ?>
            </tbody>
        </table>
    </body>
</html>