<?php echo $this->translate("workshop-instructor-takeRoll:header"); ?>
<br /><br />
<a id="checkAll" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate("workshop-instructor-takeRoll:checkAll"); ?><span class="ui-icon ui-icon-check"></span></a>
<a id="uncheckAll" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate("workshop-instructor-takeRoll:uncheckAll"); ?><span class="ui-icon ui-icon-radio-on"></span></a>
<?php echo $this->form; ?>