<div id="evaluationHelp">
	<div class="nav left">
		<a href="#" id="previous">
		<span id="left_arrow"></span>
		</a>
	</div>
	
	<div class="middle">
		<div class="slides">
		
			<div class="slide">
				<div class="slide-header">
					Getting Started With Evaluation Forms
				</div>
				<div class="slide-contents">
					Classmate now provides a new method of retrieving and displaying instructor evaluations!
					<br />
					The two options for evaluations are:
						<ul>
							<li>
								<strong>Default:</strong> this is the default evaluation for Classmate. The questions in this evaluation will be generic questions created by your content manager.
								<br />
								<strong>Requires:</strong>
									<ul style="margin-top : 2px;">
										<li>Nothing! Just select this option and continue creating your event!</li>
									</ul>
							</li>
							<li>
								<strong>Google Forms:</strong> use a custom Google Form for your evaluations. The questions asked in this evaluation are under your control, allowing you to ask more specific questions.
								<br />
								<strong>Requires:</strong>
									<ul style="margin-top : 2px;">
										<li>
											A Google Docs account with an empty spreadsheet created to store the data.
										</li>
										<li>
											The special keys to access the form and the answer sheet for display on Classmate.
										</li>
									</ul>
							</li>
						</ul>
						Click the next arrow for instructions on how to use a Google Form to manage your evaluations.
				</div>
			</div>
			
			<div class="slide">
				<div class="slide-header">
					Google Forms: Getting the '&lt;embed&gt;' Code
				</div>
				<div class="slide-contents">
					To embed your Google Form in Classmate, we need the embed code from your Google Form.
					<ul>
						<li>First open your spreadsheet document.</li>
						<li>If you have a form already created, click on <strong>Form &gt; Edit Form</strong>. A new window should appear.</li>
						<li>If you do not have a form already created, click on <strong>Tools &gt; Form &gt; Create a form</strong>. A new window should appear.</li>
						<li>In the new window, click on <strong>More actions &gt; Embed</strong>. A pop-up window should appear.</li>
						<li>Copy the code provide in the pop-up window and paste it into the <strong>Google Form Question Key</strong> box.</li>
					</ul>
					<img width="500" src="<?php echo $this->baseUrl(); ?>/images/help/embedForm.png" />
				</div>
			</div>
			
			<div class="slide">
				<div class="slide-header">
					Google Forms: Getting the Answer Code
				</div>
				<div class="slide-contents">
					To display the evaluation results on Classmate, we need your form's publish URL.
					<ul>
						<li>Open your spreadsheet document.</li>
						<li>Click the Share button at the top right of the window and select <strong>Publish as a web page</strong>. A pop-up window should appear.<img width="250" src="<?php echo $this->baseUrl(); ?>/images/help/publishForm.png" /></li>
						<li>Click the <strong>Start publishing</strong> button. The <strong>Get a link to the published data</strong> section should then populate.</li>
						<li>Copy the URL in the text area at the bottom of the window and paste it into the <strong>Google Form Answer Key</strong> box.</li>
					</ul> 
				</div>
			</div>
			
			<div class="slide">
				<div class="slide-header">
					Google Forms: Resources
				</div>
				<div class="slide-contents">
					That's it! The Google Forms will be displayed instead of the default evaluation form.
					<br />
					<br />
					For more information about Google Forms and the options available to you, visit the official help pages:
					<ul style="list-style : none;">
						<li><a style="color : #A00;" href="https://docs.google.com/support/bin/answer.py?answer=87809" target="_blank">Creating a form</a></li>
						<li><a style="color : #A00;" href="https://docs.google.com/support/bin/answer.py?answer=141062" target="_blank">Editing the form</a></li>
						<li><a style="color : #A00;" href="https://docs.google.com/support/bin/answer.py?answer=139706" target="_blank">Viewing responses</a></li>
					</ul>
				</div>
			</div>
			
		</div>
	</div>
		
	<div class="nav right">
		<a href="#" id="next">
			<span id="right_arrow"></span>
		</a>
	</div>
		

</div>
