<a href="<?php echo $this->url(array('module' => 'workshop', 'controller' => 'location'), 'default', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate("workshop-location-details:linkBack"); ?><span class="ui-icon ui-icon-triangle-1-w"></span></a>
<?php if ($this->acl['edit']) : ?>
<a href="<?php echo $this->url(array('module' => 'workshop', 'controller' => 'location', 'action' => 'edit', 'locationId' => $this->location->locationId), 'default', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate("form-button-edit"); ?><span class="ui-icon ui-icon-pencil"></span></a>
<?php endif; ?>
<?php if ($this->acl['delete']) : ?>
<a href="<?php echo $this->url(array('module' => 'workshop', 'controller' => 'location', 'action' => 'delete', 'locationId' => $this->location->locationId), 'default', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate("form-button-del"); ?><span class="ui-icon ui-icon-minusthick"></span></a>
<?php endif; ?>
<br /><br /><br />
 
	<input type="hidden" name="locationId" id="locationId" value="<?php echo $this->location->locationId; ?>" />   
	<div id="titleContainer">	    
        <?php if ($this->location->status == 'disabled') : ?>
        <div id="disabled">
        	<span class="ui-icon ui-icon-closethick" style="float:left;"></span><span class="disabledText">DISABLED! </span><?php echo $this->translate("workshop-location:disabled"); ?>
        </div>
        <?php endif; ?>
		<span id="name" rel="type=input&size=40&url=<?php echo $this->url(array('module' => 'workshop', 'controller' => 'location', 'action' => 'edit', 'response' => 'response'), 'default', true); ?>"><?php echo $this->location->name; ?></span>
	</div>
	<div id="addressContainer">
	    <?php if ($this->location->address != '') : ?>
	    <div id="address" rel="type=input&size=40&url=<?php echo $this->url(array('module' => 'workshop', 'controller' => 'location', 'action' => 'edit', 'response' => 'response'), 'default', true); ?>"><?php echo ($this->location->address == '') ? $this->translate("workshop-location:noAddress") : $this->location->address; ?></div>
	    <div id="mapit">
	    	<a href="http://maps.google.com/maps?f=q&hl=en&geocode=&q=<?php echo $this->location->address; ?>&ie=UTF8&z=16&iwloc=addr" target="_blank"><img width="25" src="/classmate/images/maps_marker.png" title="<?php echo $this->translate("workshop-location:googleMap"); ?>" /></a>
<!--	    	<a href="http://maps.google.com/maps?f=q&hl=en&geocode=&q=<?php echo $this->location->address; ?>&ie=UTF8&z=16&iwloc=addr" target="_blank"><?php echo $this->translate("workshop-location:googleMap"); ?></a>-->
	    </div>
	    <?php endif; ?>    
	     
	</div>
	<div id="typeContainer">
		<div id="typeName">
			<span>Location type:</span>
			<?php echo $this->location->locationType['name'];?>
		</div>
		<div id="typeDescription">
			<span>Location Description:</span>
			<?php echo $this->location->locationType['description'] != ''? $this->location->locationType['description'] : $this->translate("workshop-index-details:noDescription");?>
		</div>
	</div>	 
	<div id="capacityContainer">	
	   <b><?php echo $this->translate("workshop-location-details:maxStudents"); ?></b> <span id="capacity" rel="type=input&size=5&url=<?php echo $this->url(array('module' => 'workshop', 'controller' => 'location', 'action' => 'edit', 'response' => 'response'), 'default', true); ?>"><?php echo $this->location->capacity; ?></span>
    </div>
	<div id="description"><?php echo ($this->location['description'] == '') ? $this->translate("workshop-index-details:noDescription") : $this->location['description']; ?></div>