<div>
    <?php echo $this->translate("workshop-location-index:header"); ?>
    <br /><br />

    <?php if ($this->acl['add']) : ?>
    <a href="<?php echo $this->baseUrl(); ?>/workshop/location/add/" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate("workshop-location-index:linkAdd"); ?><span class="ui-icon ui-icon-plusthick"></span></a><br /><br />
    <?php endif; ?>
	
    <?php if ($this->locations->count() > 0) : ?>
        <?php foreach ($this->locations as $location) : ?>
    	    <?php if (($location->status == 'disabled' && $this->acl['viewDisabled']) || $location->status == 'enabled') : ?>
    	    <div class="location">
    	        <img src="<?php echo $this->baseUrl(); ?>/public/images/network-idle.png" alt="<?php echo $location->name; ?>" />
    	        <div class="name">
    	           <?php if ($location->status == 'disabled') : ?>
                      <b><?php echo $this->translate("workshop-location:disabled"); ?></b> &nbsp; 
                   <?php endif; ?>
                   <a href="<?php echo $this->baseUrl(); ?>/workshop/location/details/?locationId=<?php echo $location->locationId; ?>"><?php echo $location->name; ?></a></div>
    	        <?php if ($location->address != '') : ?>
    	        <div class="mapit"><a href="http://maps.google.com/maps?f=q&hl=en&geocode=&q=<?php echo $location->address; ?>&ie=UTF8&z=16&iwloc=addr" target="_blank"><?php echo $this->translate("workshop-location:googleMap"); ?></a></div>        
    	        <div class="address"><?php echo $location->address; ?></div>
    	        <?php else : ?>
    	        <div><?php echo $this->translate("workshop-location:noAddress"); ?></div>
    	        <?php endif; ?>
    	    </div>
    	    <?php endif; ?>
        <?php endforeach; ?>
    <?php else : ?>
    <?php echo $this->translate("workshop-location-index:noLocations"); ?>
    <?php endif; ?>
</div>